service: music-api
frameworkVersion: '2'

custom:
  tableName: 'music-table-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamManagedPolicies: 
    - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
    - arn:aws:iam::aws:policy/AmazonSQSFullAccess
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - s3:ListBucket
        - s3:GetObject
        - s3:ListObjects

      Resource:
        - { "Fn::GetAtt": ["MusicDynamoDBTable", "Arn" ] }
  environment:
    MUSIC_TABLE: ${self:custom.tableName}

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-express

functions:
  auth:
    handler: auth.handler

  hello:
    handler: handler.hello
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http:
          method: ANY
          path: /{proxy+}
          cors: true
          authorizer:
            name: auth
            type: request
            identitySource: method.request.header.authorization

  # getGenre:
  #   handler: index.handler
  #   events:
  #     - http: 'GET /genres'
  getGenre:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /genres
          cors: true
          authorizer:
            name: auth
            type: request
            identitySource: method.request.header.authorization

  # getArtistByGenre:
  #   handler: index.handler
  #   events:
  #     - http: 'GET /artist/by/genre/{proxy+}'
  getArtistByGenre:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /artist/by/genre/{proxy+}
          cors: true
          authorizer:
            name: auth
            type: request
            identitySource: method.request.header.authorization

  # getAlbumByArtist:
  #   handler: index.handler
  #   events:
  #     - http: 'GET /albums/by/artist/{proxy+}'
  getAlbumByArtist:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /albums/by/artist/{proxy+}
          cors: true
          authorizer:
            name: auth
            type: request
            identitySource: method.request.header.authorization

  # getSongByAlbum:
  #   handler: index.handler
  #   events:
  #     - http: 'GET /songs/by/album/{proxy+}'
  getSongByAlbum:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /songs/by/album/{proxy+}
          cors: true
          authorizer:
            name: auth
            type: request
            identitySource: method.request.header.authorization

  # getSong:
  #   handler: index.handler
  #   events:
  #     - http: 'GET /song/{proxy+}'
  getSong:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /song/{proxy+}
          cors: true
          authorizer:
            name: auth
            type: request
            identitySource: method.request.header.authorization

  sqs_function:
    handler: sqs_handler.handler
    reservedConcurrency: 10 #Concurrency control
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
  play:
    handler: index.handler
    events:
      - http:
          path: /play
          method: post
          cors:
            origin:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
              - Access-Control-Request-Headers
              - Access-Control-Request-Method
            allowCredentials: true
          authorizer:
            name: auth
            type: request
            identitySource: method.request.header.authorization          

  s3:
    handler: s3_handler.hello
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 's3:ListBucket'
        Resource: "arn:aws:s3:::hw-bucket-name"

      - Effect: 'Allow'
        Action:
          - 's3:ListObjects'
        Resource: "arn:aws:s3:::hw-bucket-name"
    events:
      - httpApi:
          path: /s3
          method: get

resources:
  Resources:
    MusicDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "pk"
            AttributeType: "S"
          -
            AttributeName: "sk"
            AttributeType: "S"

        KeySchema:
          -
            AttributeName: "pk"
            KeyType: HASH
          -
            AttributeName: "sk"
            KeyType: RANGE
          

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

        TableName: ${self:custom.tableName} 
          
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"


  # hello:
  #   handler: handler.api
  #   events:
  #    - httpApi:
  #        path: /ex
  #        method: get
  # heyo:
  #   runtime: python3.8
  #   handler: py_handler.heyo
  #   events:
  #    - httpApi:
  #        path: /heyo
  #        method: get
  # s3:
  #   handler: s3_handler.hello
  #   iamRoleStatements:
  #     - Effect: 'Allow'
  #       Action:
  #         - 's3:ListBucket'
  #       Resource: "arn:aws:s3:::hw-bucket-name"

  #     - Effect: 'Allow'
  #       Action:
  #         - 's3:ListObjects'
  #       Resource: "arn:aws:s3:::hw-bucket-name"
  #   events:
  #     - httpApi:
  #         path: /s3
  #         method: get